artifacts_root: artifacts

data_ingestion:
root_dir: artifacts/data_ingestions
source_url: https://github.com/aditim1996/PRACTICE_DS_PROJECTS/raw/refs/heads/main/winequality-red.csv.zip
loca_data_file: artifacts/data_ingestion/data.zip
unzip_dir: artifacts/data_ingestions